[project]
name = "langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-anthropic>=0.3.3",
    "langchain-google-genai>=2.0.9",
    "langchain-openai>=0.2.14",
    "python-dotenv>=1.0.1",
]
